### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by GS-726** [Feaxure-fresh/TL-Bearing-Fault-Diagnosis#26]
该项目是否能在没有gpu的电脑上运行，如果可以运行，那么代码中和gpu相关的代码需要怎么修改，而且对于参数cuda_device的描述，将其设置为0是否可以认为是不使用gpu，代码中对该参数的help中提到（‘ ’意味着使用cpu），这个‘ ’是表示空字符串的意思，还是说表示其他意思。我已经尝试过一些方法，但总是提示该错误（AssertionError: Torch not compiled with CUDA enabled），我不确定是不是因为有些调用gpu的代码漏掉了。

**Comment by Feaxure-fresh** [comment]
parser.add_argument('--cuda_device', type=str, default='0', help='Allocate the device to use only one GPU ('' means using cpu)')
修改default=''或者在运行代码时设置--cuda_device ''即可cpu运行。

**Comment by GS-726** [comment]
感谢，已解决
